CREATE TABLE IF NOT EXISTS player_stats (
    id INT AUTO_INCREMENT PRIMARY KEY,
    game_id VARCHAR(250) NOT NULL,
    season INT NOT NULL,
    player_name VARCHAR(250),
    player_id INT,
    team VARCHAR(250),
    opponent VARCHAR(250),
    numdate INT,
    datetext VARCHAR(20),
    opstyle INT,
    quality INT,
    win1 INT,
    muid VARCHAR(250),
    win2 INT,
    Min_per DECIMAL(10, 2),
    ORtg DECIMAL(10, 2),
    useage DECIMAL(10, 2),
    eFG DECIMAL(10, 2),
    TS_per DECIMAL(10, 2),
    ORB_per DECIMAL(10, 2),
    DRB_per DECIMAL(10, 2),
    AST_per DECIMAL(10, 2),
    TO_per DECIMAL(10, 2),
    dunksmade INT,
    dunksatt INT,
    rimmade INT,
    rimatt INT,
    midmade INT,
    midatt INT,
    twoPM DECIMAL(10, 2),
    twoPA DECIMAL(10, 2),
    TPM DECIMAL(10, 2),
    TPA DECIMAL(10, 2),
    FTM DECIMAL(10, 2),
    FTA DECIMAL(10, 2),
    bpm_rd DECIMAL(10, 2),
    Obpm DECIMAL(10, 4),
    Dbpm DECIMAL(10, 4),
    bpm_net DECIMAL(10, 2),
    pts INT,
    ORB DECIMAL(10, 2),
    DRB DECIMAL(10, 2),
    AST DECIMAL(10, 2),
    TOV DECIMAL(10, 2),
    STL DECIMAL(10, 2),
    BLK DECIMAL(10, 2),
    stl_per DECIMAL(10, 2),
    blk_per DECIMAL(10, 2),
    PF DECIMAL(10, 2),
    possessions DECIMAL(10, 4),
    bpm DECIMAL(10, 4),
    sbpm DECIMAL(10, 4),
    loc VARCHAR(10),
    inches INT,
    cls VARCHAR(10),
    UNIQUE KEY unique_player_game (game_id, player_id),
    INDEX idx_game_id (game_id),
    INDEX idx_player_id (player_id),
    INDEX idx_team (team),
    INDEX idx_season (season),
    FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE
);
